name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build Spring Boot Backend
      - name: Build Spring Boot Backend
        run: mvn clean install -DskipTests
        working-directory: ./E-commerceMiniStore-main

      # 4. Copy PEM Key
      - name: Copy PEM key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > ministore-key.pem

      # 5. Fix permissions
      - name: Set PEM permissions
        run: chmod 600 ministore-key.pem

      # 6. Copy JAR to EC2
      - name: Upload JAR to EC2
        run: |
          scp -i ministore-key.pem -o StrictHostKeyChecking=no \
          target/E-commerceMiniStore-0.0.1-SNAPSHOT.jar \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/home/ubuntu/app/

      # 7. Restart App
      - name: Restart App
        run: |
          ssh -i ministore-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          pkill -f E-commerceMiniStore-0.0.1-SNAPSHOT.jar || true
          nohup java -jar /home/ubuntu/app/E-commerceMiniStore-0.0.1-SNAPSHOT.jar > /home/ubuntu/app/app.log 2>&1 &
          EOF

